# Generated by Django 5.2.8 on 2025-11-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_patientrecord_doctor_record'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patient.patient'),
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
    ]
