# Generated by Django 5.2.9 on 2026-01-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doctor', '0005_doctor_groups_doctor_is_active_doctor_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, default='Unknown Hospital', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
